package br.com.joyC.gaals;

public interface ScannerConstants
{

    int[] TOKEN_STATE = {-1,  0, -1, 12, -1,  8, -1, -1, -1, -1, -1,  2, 10, -1, -1, -1, -1, -1, -1, -1, -1, -1,  9,  6,  7,  4,  3,  5, 11,  6, -1,  7, -1,  4, -1,  3, -1,  5, -1, -1,  6, -1,  7, -1,  4, -1,  3, -1,  5, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 };

    String[] SCANNER_ERROR =
    {
        "Caractere não esperado",
        "",
        "Erro identificando string",
        "",
        "Erro identificando comBloco",
        "",
        "Erro identificando idBool",
        "Erro identificando idComposto",
        "Erro identificando idFloat",
        "Erro identificando idInt",
        "Erro identificando idString",
        "",
        "",
        "Erro identificando comBloco",
        "Erro identificando float",
        "Erro identificando idBool",
        "Erro identificando idComposto",
        "Erro identificando idFloat",
        "Erro identificando idInt",
        "Erro identificando idString",
        "Erro identificando palavraReservada",
        "Erro identificando comBloco",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Erro identificando idBool",
        "",
        "Erro identificando idComposto",
        "",
        "Erro identificando idFloat",
        "",
        "Erro identificando idInt",
        "",
        "Erro identificando idString",
        "Erro identificando idBool",
        "",
        "Erro identificando idComposto",
        "",
        "Erro identificando idFloat",
        "",
        "Erro identificando idInt",
        "",
        "Erro identificando idString",
        "",
        "Erro identificando idBool",
        "Erro identificando idComposto",
        "Erro identificando idFloat",
        "Erro identificando idInt",
        "Erro identificando idString",
        "Erro identificando idBool",
        "Erro identificando idComposto",
        "Erro identificando idFloat",
        "Erro identificando idInt",
        "Erro identificando idString"
    };

}
